CXX = g++
CXXFLAGS = -Iinclude -Wall -Wextra -std=c++17
SRC = basic.cpp
OBJ = $(SRC:.cpp=.o)
TARGET = my_project

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CXX) $(OBJ) -o $(TARGET)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ) $(TARGET)
